plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.yunjin.wanttoreadoriginals'
    compileSdk 35

    defaultConfig {
        applicationId 'com.yunjin.wanttoreadoriginals'
        minSdk 31
        targetSdk 35
        versionCode 3
        versionName '0.3-spen-button'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.15.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.activity:activity-ktx:1.9.3'
    implementation 'androidx.fragment:fragment-ktx:1.8.5'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.0'
    implementation 'androidx.pdf:pdf-viewer-fragment:1.0.0-alpha18'
    implementation 'androidx.pdf:pdf-viewer:1.0.0-alpha18'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'org.json:json:20240303'
}
